apiVersion: v1
kind: Template
labels:
  template: user-api-deployment
  thoth: 0.1.0
metadata:
  name: user-api-deployment
  annotations:
    description: This is Thoth Core - User API
    openshift.io/display-name: 'Thoth Core: User API'
    version: 0.4.0
    tags: poc,thoth,user-api,ai-stacks
    template.openshift.io/documentation-url: https://github.com/Thoth-Station/
    template.openshift.io/long-description: >
      This template defines resources needed to deploy Thoth Core Services as
      a Proof-of-Concept to OpenShift.
    template.openshift.io/provider-display-name: Red Hat, Inc.

objects:
  - kind: Route
    apiVersion: v1
    metadata:
      name: user-api
      namespace: ${THOTH_FRONTEND_NAMESPACE}
      labels:
        app: thoth-core
        component: user-api
    spec:
      to:
        kind: Service
        name: user-api

  - kind: Service
    apiVersion: v1
    metadata:
      labels:
        service: user-api
        app: thoth-core
        component: user-api
      name: user-api
      namespace: ${THOTH_FRONTEND_NAMESPACE}
    spec:
      ports:
        - port: 80
          protocol: TCP
          targetPort: 8080
      selector:
        service: user-api

# Deployment configs
- apiVersion: v1
  kind: DeploymentConfig
  metadata:
    labels:
      service: user-api
      app: thoth-core
      component: user-api
    name: user-api
    namespace: ${THOTH_FRONTEND_NAMESPACE}
  spec:
    replicas: 1
    selector:
      service: user-api
    template:
      metadata:
        labels:
          service: user-api
      spec:
        serviceAccountName: analyzer
        containers:
        - env:
          - name: APP_MODULE
            value: 'thoth_user_api.entrypoint:app'
          - name: APP_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                key: user-api-service-port
                name: thoth
          - name: KUBERNETES_API_URL
            value: 'https://kubernetes.default.svc.cluster.local'
          - name: KUBERNETES_VERIFY_TLS
            value: "0"
          - name: THOTH_RESULT_API_URL
            value: http://result-api
          - name: THOTH_MIDDLETIER_POD_CPU_LIMIT
            valueFrom:
              configMapKeyRef:
                key: middletier-pod-cpu-limit
                name: thoth
          - name: THOTH_MIDDLETIER_POD_MEMORY_LIMIT
            valueFrom:
              configMapKeyRef:
                key: middletier-pod-memory-limit
                name: thoth
          - name: THOTH_MIDDLETIER_NAMESPACE
            valueFrom:
              configMapKeyRef:
                key: middletier-namespace
                name: thoth
          - name: THOTH_BACKEND_NAMESPACE
            valueFrom:
              configMapKeyRef:
                key: backend-namespace
                name: thoth
          - name: THOTH_DEPLOYMENT_NAME
            valueFrom:
              configMapKeyRef:
                key: storage-bucket-name
                name: thoth
          - name: THOTH_S3_ENDPOINT_URL
            valueFrom:
              configMapKeyRef:
                key: ceph-host
                name: thoth
          - name: THOTH_CEPH_BUCKET
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-name
                name: thoth
          - name: THOTH_CEPH_BUCKET_PREFIX
            valueFrom:
              configMapKeyRef:
                key: ceph-bucket-prefix
                name: thoth
          - name: THOTH_SECRET
            valueFrom:
              secretKeyRef:
                name: thoth
                key: thoth-secret
          - name: THOTH_JANUSGRAPH_HOST
            value: janusgraph
          - name: THOTH_JANUSGRAPH_PORT
            value: '80'
          - name: THOTH_USER_API_APP_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: thoth
                key: app-secret-key
          - name: THOTH_CEPH_KEY_ID
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-key-id
          - name: THOTH_CEPH_SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: thoth
                key: ceph-secret-key
          - name: RSYSLOG_HOST
            valueFrom:
             configMapKeyRef:
               key: rsyslog-host
               name: thoth
          - name: RSYSLOG_PORT
            valueFrom:
             configMapKeyRef:
               key: rsyslog-port
               name: thoth
          - name: PROMETHEUS_PUSHGATEWAY_HOST
            valueFrom:
             configMapKeyRef:
               key: prometheus-pushgateway-host
               name: thoth
          - name: PROMETHEUS_PUSHGATEWAY_PORT
            valueFrom:
             configMapKeyRef:
               key: prometheus-pushgateway-port
               name: thoth
          name: user-api
          ports:
            - containerPort: 8080
              protocol: TCP
          resources:
            requests:
              memory: "256Mi"
              cpu: "250m"
            limits:
              memory: "256Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: '/readiness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 10
          livenessProbe:
            httpGet:
              path: '/liveness'
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 5
            periodSeconds: 60
            timeoutSeconds: 10
    test: false
    triggers:
    - type: ConfigChange
    - type: ImageChange
      imageChangeParams:
        automatic: true
        containerNames:
          - user-api
        from:
          kind: ImageStreamTag
          name: 'user-api:latest'

  - kind: ImageStream
    apiVersion: v1
    metadata:
      labels:
        app: thoth-core
      name: user-api
      namespace: ${THOTH_FRONTEND_NAMESPACE}
    spec:
      name: latest

parameters:
  - displayName: Thoth Frontend Namespace
    description: Name of the Thoth Frontend Namespace
    required: true
    name: THOTH_FRONTEND_NAMESPACE
